// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6kMAgmaTNyhz3FvZHiB1gwKO4iNkOfuA',
    appId: '1:1099189591506:web:26be762b3e2372dbcc7c0b',
    messagingSenderId: '1099189591506',
    projectId: 'quiz-app-int2-final',
    authDomain: 'quiz-app-int2-final.firebaseapp.com',
    storageBucket: 'quiz-app-int2-final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTZRNYyy842qscBtoBFHUC86Q3QaGydiU',
    appId: '1:1099189591506:android:2f06723448ae7680cc7c0b',
    messagingSenderId: '1099189591506',
    projectId: 'quiz-app-int2-final',
    storageBucket: 'quiz-app-int2-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDibsXAatkd-E9TqIfMWLOvq3I1XrB2GNI',
    appId: '1:1099189591506:ios:19a5a6cef22f8797cc7c0b',
    messagingSenderId: '1099189591506',
    projectId: 'quiz-app-int2-final',
    storageBucket: 'quiz-app-int2-final.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDibsXAatkd-E9TqIfMWLOvq3I1XrB2GNI',
    appId: '1:1099189591506:ios:19a5a6cef22f8797cc7c0b',
    messagingSenderId: '1099189591506',
    projectId: 'quiz-app-int2-final',
    storageBucket: 'quiz-app-int2-final.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6kMAgmaTNyhz3FvZHiB1gwKO4iNkOfuA',
    appId: '1:1099189591506:web:fdaa4e613c9bf94dcc7c0b',
    messagingSenderId: '1099189591506',
    projectId: 'quiz-app-int2-final',
    authDomain: 'quiz-app-int2-final.firebaseapp.com',
    storageBucket: 'quiz-app-int2-final.firebasestorage.app',
  );

}